const CUSTOM_LISTINGS_KEY = "khl_custom_listings";

export const MARKETPLACE_CATEGORIES = [
  { id: "all", label: "All" },
  { id: "airbnb", label: "Airbnbs" },
  { id: "home", label: "Homes" },
  { id: "hotel", label: "Hotels" },
  { id: "restaurant", label: "Restaurants" }
];

const SELLER_PHONE_BOOK = {
  "gift-seller@khl.app": "254712345678",
  "garden-seller@khl.app": "254723456789",
  "urban-seller@khl.app": "254734567891",
  "rift-seller@khl.app": "254745678912",
  "lake-seller@khl.app": "254756789123",
  "highland-seller@khl.app": "254767891234",
  "coast-seller@khl.app": "254778912345"
};

const buildListing = (id, category, title, price, location, tag, sellerEmail, sellerName, description, imageUrl) => ({
  id,
  category,
  title,
  price,
  location,
  tag,
  sellerEmail,
  sellerName,
  sellerPhone: SELLER_PHONE_BOOK[sellerEmail] || "",
  imageUrl,
  description
});


const storage = {
  get: (key) => {
    try {
      const data = localStorage.getItem(key);
      return data ? JSON.parse(data) : [];
    } catch {
      return [];
    }
  },
  set: (key, value) => {
    localStorage.setItem(key, JSON.stringify(value));
    window.dispatchEvent(new CustomEvent("listings:updated"));
  }
};

export const getCustomListings = () => {
  const listings = storage.get(CUSTOM_LISTINGS_KEY);
  return Array.isArray(listings) ? listings : [];
};

export const saveCustomListing = (listing) => {
  const listings = getCustomListings();
  storage.set(CUSTOM_LISTINGS_KEY, [...listings, listing]);
};

export const seedListings = [
  buildListing("home-westlands-loft", "home", "Sunlit city loft", "Ksh 25,000 / month", "Westlands", "Popular", "gift-seller@khl.app", "Gift Homes", "A bright apartment near shopping, co-working, and evening hotspots.", "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-kilimani-suite", "home", "Modern two-bedroom suite", "Ksh 40,000 / month", "Kilimani", "Premium", "gift-seller@khl.app", "Gift Homes", "Designed for long stays with secure parking and a clean modern finish.", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-karen-cottage", "home", "Garden cottage retreat", "Ksh 38,000 / month", "Karen", "Featured", "garden-seller@khl.app", "Garden Estates", "Quiet leafy surroundings with warm interiors and generous outdoor space.", "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-ruaka-flat", "home", "Ruaka commuter flat", "Ksh 24,000 / month", "Ruaka", "Value", "urban-seller@khl.app", "Urban Nest", "A practical apartment for shoppers, commuters, and first-time renters.", "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-southb-pad", "home", "South B starter apartment", "Ksh 27,000 / month", "South B", "Trending", "urban-seller@khl.app", "Urban Nest", "Compact but polished, with quick access to town and transport links.", "https://images.unsplash.com/photo-1464890100898-a385f744067f?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-runda-view", "home", "Runda garden apartment", "Ksh 32,000 / month", "Runda", "Premium", "garden-seller@khl.app", "Garden Estates", "A serene home with green views and a quieter residential feel.", "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-nakuru-hill", "home", "Nakuru hillside home", "Ksh 30,000 / month", "Nakuru", "New", "rift-seller@khl.app", "Rift Valley Lets", "Family-friendly home with open living space and easy town access.", "https://images.unsplash.com/photo-1600566752734-810f8aa4a2c8?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-kisumu-lake", "home", "Lakeside executive home", "Ksh 35,000 / month", "Kisumu", "Featured", "lake-seller@khl.app", "Lakefront Living", "Smart layout, good ventilation, and access to the city waterfront.", "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-nyeri-cool", "home", "Nyeri cool-climate apartment", "Ksh 31,500 / month", "Nyeri", "Popular", "highland-seller@khl.app", "Highland Homes", "Balanced comfort and climate with a polished executive look.", "https://images.unsplash.com/photo-1600607687644-c7171b42498f?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-nanyuki-mountain", "home", "Nanyuki scenic residence", "Ksh 42,000 / month", "Nanyuki", "Premium", "highland-seller@khl.app", "Highland Homes", "Mountain-town calm with spacious interiors and flexible living areas.", "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=900&q=80"),
  buildListing("airbnb-nyali-breeze", "airbnb", "Nyali breezy stay", "Ksh 8,500 / night", "Nyali", "Popular", "coast-seller@khl.app", "Coastline Hosts", "Short-stay apartment with balcony seating and easy beach access.", "https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=900&q=80"),
  buildListing("airbnb-diani-villa", "airbnb", "Diani pool villa", "Ksh 15,000 / night", "Diani", "Premium", "coast-seller@khl.app", "Coastline Hosts", "Private villa stay built for group getaways and relaxed weekends.", "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80"),
  buildListing("airbnb-kilimani-weekend", "airbnb", "Kilimani weekend studio", "Ksh 6,900 / night", "Kilimani", "Value", "urban-seller@khl.app", "Urban Nest", "A central city escape for short work trips or weekend plans.", "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=900&q=80"),
  buildListing("airbnb-westlands-exec", "airbnb", "Westlands executive stay", "Ksh 9,800 / night", "Westlands", "Featured", "gift-seller@khl.app", "Gift Homes", "Designed for business travelers who want comfort and nightlife nearby.", "https://images.unsplash.com/photo-1519643381401-22c77e60520e?auto=format&fit=crop&w=900&q=80"),
  buildListing("airbnb-naivasha-lake", "airbnb", "Naivasha lake getaway", "Ksh 11,500 / night", "Naivasha", "Trending", "rift-seller@khl.app", "Rift Valley Lets", "Relaxed stay for couples and small groups near scenic attractions.", "https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=900&q=80"),
  buildListing("airbnb-nanyuki-loft", "airbnb", "Nanyuki mountain loft", "Ksh 10,200 / night", "Nanyuki", "New", "highland-seller@khl.app", "Highland Homes", "A cozy short-stay loft with crisp air and scenic touches.", "https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=900&q=80"),
  buildListing("airbnb-lamu-hideaway", "airbnb", "Lamu heritage hideaway", "Ksh 12,800 / night", "Lamu", "Premium", "coast-seller@khl.app", "Coastline Hosts", "Swahili-inspired interiors for travelers who want charm and calm.", "https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=900&q=80"),
  buildListing("airbnb-eldoret-calm", "airbnb", "Eldoret calm stay", "Ksh 5,700 / night", "Eldoret", "Affordable", "rift-seller@khl.app", "Rift Valley Lets", "A quiet furnished stopover for visitors, medics, and traveling families.", "https://images.unsplash.com/photo-1416331108676-a22ccb276e35?auto=format&fit=crop&w=900&q=80"),
  buildListing("airbnb-meru-view", "airbnb", "Meru hillside apartment", "Ksh 6,100 / night", "Meru", "Popular", "highland-seller@khl.app", "Highland Homes", "Compact and scenic, with a practical furnished short-stay setup.", "https://images.unsplash.com/photo-1600047509782-20d39509f26d?auto=format&fit=crop&w=900&q=80"),
  buildListing("airbnb-malindi-sun", "airbnb", "Malindi sunny suite", "Ksh 7,400 / night", "Malindi", "Value", "coast-seller@khl.app", "Coastline Hosts", "A breezy suite for holidaymakers looking for simple comfort near town.", "https://images.unsplash.com/photo-1600585154154-712ea3e519b8?auto=format&fit=crop&w=900&q=80"),
  buildListing("hotel-nairobi-sky", "hotel", "Nairobi Sky Hotel", "Ksh 12,500 / night", "Upper Hill", "Premium", "gift-seller@khl.app", "Gift Stays", "Business-friendly hotel with meeting rooms, breakfast, and airport transfers.", "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80"),
  buildListing("hotel-mombasa-coral", "hotel", "Coral Bay Hotel", "Ksh 14,200 / night", "Mombasa", "Featured", "coast-seller@khl.app", "Coastline Hosts", "A coastal hotel for family stays, conference travel, and beach weekends.", "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=900&q=80"),
  buildListing("hotel-kisumu-harbor", "hotel", "Harbor View Hotel", "Ksh 10,800 / night", "Kisumu", "Popular", "lake-seller@khl.app", "Lakefront Living", "A polished city hotel with lake views and strong business amenities.", "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=900&q=80"),
  buildListing("hotel-nakuru-golden", "hotel", "Golden Rift Hotel", "Ksh 9,900 / night", "Nakuru", "Value", "rift-seller@khl.app", "Rift Valley Lets", "Comfortable rooms and easy access for road trips and events.", "https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?auto=format&fit=crop&w=900&q=80"),
  buildListing("hotel-nyeri-highland", "hotel", "Highland Crown Hotel", "Ksh 11,400 / night", "Nyeri", "New", "highland-seller@khl.app", "Highland Homes", "A refined mountain-town hotel built for quiet, polished stays.", "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=900&q=80"),
  buildListing("hotel-diani-coast", "hotel", "Diani Coast Resort", "Ksh 16,000 / night", "Diani", "Premium", "coast-seller@khl.app", "Coastline Hosts", "A resort stay with poolside relaxation and premium guest services.", "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=900&q=80"),
  buildListing("hotel-thika-express", "hotel", "Thika Express Suites", "Ksh 8,600 / night", "Thika", "Affordable", "urban-seller@khl.app", "Urban Nest", "Short-stay rooms for road travelers, meetings, and overnight stops.", "https://images.unsplash.com/photo-1455587734955-081b22074882?auto=format&fit=crop&w=900&q=80"),
  buildListing("hotel-eldoret-elite", "hotel", "Eldoret Elite Hotel", "Ksh 10,300 / night", "Eldoret", "Featured", "rift-seller@khl.app", "Rift Valley Lets", "Balanced comfort and polished hospitality for work and family trips.", "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=900&q=80"),
  buildListing("hotel-nanyuki-frost", "hotel", "Frost Peak Lodge", "Ksh 13,700 / night", "Nanyuki", "Premium", "highland-seller@khl.app", "Highland Homes", "Cool-climate lodge feel with smart rooms and scenic design cues.", "https://images.unsplash.com/photo-1519449556851-5720b33024e7?auto=format&fit=crop&w=900&q=80"),
  buildListing("hotel-lamu-reef", "hotel", "Reef Heritage Inn", "Ksh 12,200 / night", "Lamu", "Popular", "coast-seller@khl.app", "Coastline Hosts", "A boutique hotel with heritage styling and guest-centered service.", "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80"),
  buildListing("restaurant-westlands-grill", "restaurant", "Westlands Flame Grill", "Ksh 2,800 / meal", "Westlands", "Popular", "gift-seller@khl.app", "Gift Dining", "Signature grilled plates, polished interiors, and a lively evening crowd.", "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=900&q=80"),
  buildListing("restaurant-kilimani-bistro", "restaurant", "Kilimani Social Bistro", "Ksh 2,300 / meal", "Kilimani", "Featured", "urban-seller@khl.app", "Urban Nest", "Modern casual dining for work lunches, meetups, and date nights.", "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=900&q=80"),
  buildListing("restaurant-nyali-sea", "restaurant", "Nyali Sea Table", "Ksh 3,400 / meal", "Nyali", "Premium", "coast-seller@khl.app", "Coastline Hosts", "Seafood-forward dining in a bright, breezy coastal setting.", "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=900&q=80"),
  buildListing("restaurant-kisumu-lake", "restaurant", "Lakefront Kitchen", "Ksh 2,600 / meal", "Kisumu", "Trending", "lake-seller@khl.app", "Lakefront Living", "Comfort dishes, fish specialties, and a relaxed waterfront atmosphere.", "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=900&q=80"),
  buildListing("restaurant-nakuru-garden", "restaurant", "Nakuru Garden Eatery", "Ksh 1,900 / meal", "Nakuru", "Value", "rift-seller@khl.app", "Rift Valley Lets", "Open-air dining and family-friendly comfort menus for casual outings.", "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=900&q=80"),
  buildListing("restaurant-nairobi-brunch", "restaurant", "City Brunch House", "Ksh 2,100 / meal", "Karen", "New", "garden-seller@khl.app", "Garden Estates", "A brunch and coffee favorite with quiet corners and green views.", "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=900&q=80"),
  buildListing("restaurant-eldoret-woodfired", "restaurant", "Woodfired Table", "Ksh 2,400 / meal", "Eldoret", "Popular", "rift-seller@khl.app", "Rift Valley Lets", "Known for woodfired plates and group-friendly seating arrangements.", "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=80"),
  buildListing("restaurant-meru-rooftop", "restaurant", "Meru Rooftop Lounge", "Ksh 2,700 / meal", "Meru", "Featured", "highland-seller@khl.app", "Highland Homes", "Evening views, small plates, and a premium city-center ambience.", "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=900&q=80"),
  buildListing("restaurant-mombasa-spice", "restaurant", "Spice Route Dining", "Ksh 3,100 / meal", "Mombasa", "Premium", "coast-seller@khl.app", "Coastline Hosts", "Layered coastal flavors and curated dinners for visitors and locals.", "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=900&q=80"),
  buildListing("restaurant-thika-bbq", "restaurant", "Thika Smokehouse", "Ksh 2,000 / meal", "Thika", "Affordable", "urban-seller@khl.app", "Urban Nest", "An easygoing spot for grill plates, meetups, and casual family meals.", "https://images.unsplash.com/photo-1555992336-03a23c7b20ee?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-machakos-family", "home", "Machakos family home", "Ksh 41,000 / month", "Machakos", "Featured", "rift-seller@khl.app", "Rift Valley Lets", "Open-plan comfort for larger households and longer stays.", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-lavington-elegant", "home", "Lavington elegant apartment", "Ksh 45,000 / month", "Lavington", "Premium", "gift-seller@khl.app", "Gift Homes", "Upscale finishes with secure access and city convenience.", "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-embakasi-budget", "home", "Embakasi starter studio", "Ksh 16,000 / month", "Embakasi", "Budget", "urban-seller@khl.app", "Urban Nest", "A smart starter rental for budget-conscious city living.", "https://images.unsplash.com/photo-1448630360428-65456885c650?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-kasarani-smart", "home", "Smart Kasarani bedsitter", "Ksh 18,000 / month", "Kasarani", "Affordable", "urban-seller@khl.app", "Urban Nest", "Budget-friendly city living with quick access to shops and public transport.", "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-langata-hideaway", "home", "Lang'ata hideaway", "Ksh 22,500 / month", "Lang'ata", "Value", "garden-seller@khl.app", "Garden Estates", "A calm one-bedroom rental with warm finishes and neighborhood comfort.", "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-ngongroad-urban", "home", "Ngong Road urban apartment", "Ksh 28,000 / month", "Ngong Road", "New", "urban-seller@khl.app", "Urban Nest", "Well-connected apartment ideal for commuters and city professionals.", "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-roysambu-compact", "home", "Roysambu compact home", "Ksh 19,500 / month", "Roysambu", "Affordable", "urban-seller@khl.app", "Urban Nest", "Small but polished home with a bright layout and accessible daily essentials.", "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-southc-retreat", "home", "South C retreat", "Ksh 21,000 / month", "South C", "Value", "urban-seller@khl.app", "Urban Nest", "A neat home with a balanced layout and quick city access.", "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-githurai-practical", "home", "Githurai practical studio", "Ksh 14,500 / month", "Githurai", "Budget", "urban-seller@khl.app", "Urban Nest", "A straightforward starter space focused on affordability and utility.", "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-thikaroad-exec", "home", "Thika Road executive flat", "Ksh 31,000 / month", "Thika Road", "Featured", "urban-seller@khl.app", "Urban Nest", "Executive-style rental close to malls, road links, and lifestyle spots.", "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-utawala-fresh", "home", "Utawala fresh unit", "Ksh 17,000 / month", "Utawala", "Affordable", "urban-seller@khl.app", "Urban Nest", "A fresh rental with practical finishes and room for a small family.", "https://images.unsplash.com/photo-1600607687644-c7171b42498f?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-syokimau-airport", "home", "Syokimau airport-side home", "Ksh 26,500 / month", "Syokimau", "Popular", "urban-seller@khl.app", "Urban Nest", "A comfortable home for airport workers, commuters, and traveling families.", "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-kileleshwa-sleek", "home", "Kileleshwa sleek apartment", "Ksh 33,000 / month", "Kileleshwa", "Featured", "gift-seller@khl.app", "Gift Homes", "Contemporary apartment with skyline cues and polished interiors.", "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-dagoretti-comfort", "home", "Dagoretti comfort rental", "Ksh 23,000 / month", "Dagoretti", "Value", "garden-seller@khl.app", "Garden Estates", "Comfort-first home with soft finishes and neighborhood convenience.", "https://images.unsplash.com/photo-1519643381401-22c77e60520e?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-parklands-connected", "home", "Parklands connected apartment", "Ksh 29,000 / month", "Parklands", "Trending", "gift-seller@khl.app", "Gift Homes", "Well-connected apartment with practical city access and a modern feel.", "https://images.unsplash.com/photo-1464146072230-91cabc968266?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-muthaiga-classic", "home", "Muthaiga classic home", "Ksh 36,000 / month", "Muthaiga", "Premium", "garden-seller@khl.app", "Garden Estates", "Leafy-estate living with refined proportions and quiet surroundings.", "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-donholm-polished", "home", "Donholm polished apartment", "Ksh 20,000 / month", "Donholm", "Affordable", "urban-seller@khl.app", "Urban Nest", "Polished, practical apartment for affordable everyday city living.", "https://images.unsplash.com/photo-1600047509358-9dc75507daeb?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-zimmerman-starter", "home", "Zimmerman starter home", "Ksh 15,500 / month", "Zimmerman", "Budget", "urban-seller@khl.app", "Urban Nest", "A simple starter rental with smart use of space and a compact layout.", "https://images.unsplash.com/photo-1600607687641-2c2d9c1d0f2e?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-kikuyu-duplex", "home", "Kikuyu duplex home", "Ksh 34,500 / month", "Kikuyu", "New", "rift-seller@khl.app", "Rift Valley Lets", "A suburban duplex with calm streets and family-friendly room planning.", "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-athiriver-gated", "home", "Athi River gated apartment", "Ksh 27,500 / month", "Athi River", "Popular", "rift-seller@khl.app", "Rift Valley Lets", "Modern gated-community living with a comfortable daily rhythm.", "https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-naivasha-lakeview", "home", "Naivasha lakeview residence", "Ksh 44,000 / month", "Naivasha", "Premium", "rift-seller@khl.app", "Rift Valley Lets", "A scenic executive home with resort-adjacent energy and open views.", "https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-eldoret-airy", "home", "Eldoret airy rental", "Ksh 22,000 / month", "Eldoret", "Affordable", "rift-seller@khl.app", "Rift Valley Lets", "Warm, airy rental home designed for comfort and dependable everyday use.", "https://images.unsplash.com/photo-1416331108676-a22ccb276e35?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-mombasa-breezy", "home", "Mombasa breezy apartment", "Ksh 28,500 / month", "Mombasa", "Featured", "coast-seller@khl.app", "Coastline Hosts", "Coastal apartment with natural airflow and an easy-going beach-city feel.", "https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-nyali-beachside", "home", "Nyali beachside apartment", "Ksh 24,500 / month", "Nyali", "Popular", "coast-seller@khl.app", "Coastline Hosts", "A bright beachside apartment with a short commute to the shoreline.", "https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-bamburi-coast", "home", "Bamburi coastal apartment", "Ksh 26,000 / month", "Bamburi", "Value", "coast-seller@khl.app", "Coastline Hosts", "A practical coastal apartment for tenants who want the ocean nearby.", "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-kakamega-family", "home", "Kakamega family apartment", "Ksh 33,500 / month", "Kakamega", "Featured", "lake-seller@khl.app", "Lakefront Living", "Contemporary family apartment with room for longer, calmer stays.", "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-bungoma-charming", "home", "Bungoma charming home", "Ksh 29,500 / month", "Bungoma", "New", "lake-seller@khl.app", "Lakefront Living", "A charming home with clean finishes and a welcoming neighborhood feel.", "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-meru-hillside", "home", "Meru hillside home", "Ksh 23,500 / month", "Meru", "Popular", "highland-seller@khl.app", "Highland Homes", "A fresh hillside rental with scenic views and a relaxed floor plan.", "https://images.unsplash.com/photo-1600047509782-20d39509f26d?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-embu-calm", "home", "Embu calm apartment", "Ksh 27,800 / month", "Embu", "Value", "highland-seller@khl.app", "Highland Homes", "A polished apartment with calm interiors and a low-stress location.", "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-kericho-green", "home", "Kericho green-town rental", "Ksh 18,800 / month", "Kericho", "Affordable", "highland-seller@khl.app", "Highland Homes", "Compact rental in a fresh, green town with an easy day-to-day pace.", "https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-kisii-light", "home", "Kisii light-filled apartment", "Ksh 25,800 / month", "Kisii", "Trending", "lake-seller@khl.app", "Lakefront Living", "A modern apartment with bright rooms and a comfortable urban setup.", "https://images.unsplash.com/photo-1600585154524-36cb8cf2d747?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-migori-exec", "home", "Migori executive home", "Ksh 34,000 / month", "Migori", "New", "lake-seller@khl.app", "Lakefront Living", "Executive rental with a calm interior mood and open-plan living.", "https://images.unsplash.com/photo-1600210492493-0946911123ea?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-garissa-simple", "home", "Garissa modern apartment", "Ksh 20,500 / month", "Garissa", "Affordable", "rift-seller@khl.app", "Rift Valley Lets", "Simple modern apartment designed for reliability and clean living.", "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-isiolo-openview", "home", "Isiolo open-view home", "Ksh 37,000 / month", "Isiolo", "Featured", "rift-seller@khl.app", "Rift Valley Lets", "A refined home with open views and well-proportioned living spaces.", "https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-marsabit-comfort", "home", "Marsabit comfort rental", "Ksh 22,800 / month", "Marsabit", "Value", "rift-seller@khl.app", "Rift Valley Lets", "Comfort-first rental with a clean layout and low-maintenance living.", "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-lamu-swahili", "home", "Lamu Swahili residence", "Ksh 39,000 / month", "Lamu", "Premium", "coast-seller@khl.app", "Coastline Hosts", "A Swahili-inspired residence with a calm, heritage-driven feel.", "https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-voi-clean", "home", "Voi clean apartment", "Ksh 24,800 / month", "Voi", "Popular", "rift-seller@khl.app", "Rift Valley Lets", "A clean apartment close to amenities and transport for daily ease.", "https://images.unsplash.com/photo-1600607687709-df5b28b2f3d5?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-malindi-sunny", "home", "Malindi sunny apartment", "Ksh 19,000 / month", "Malindi", "Budget", "coast-seller@khl.app", "Coastline Hosts", "A sunny coastal apartment with straightforward comfort and town access.", "https://images.unsplash.com/photo-1600585154154-712ea3e519b8?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-kilifi-relaxed", "home", "Kilifi relaxed flat", "Ksh 21,500 / month", "Kilifi", "Affordable", "coast-seller@khl.app", "Coastline Hosts", "A relaxed coastal flat with soft lighting and an easy indoor flow.", "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-diani-villa", "home", "Diani villa residence", "Ksh 47,000 / month", "Diani", "Premium", "coast-seller@khl.app", "Coastline Hosts", "Resort-inspired villa living with privacy and premium space planning.", "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-ruiru-modern", "home", "Ruiru modern apartment", "Ksh 23,800 / month", "Ruiru", "Popular", "urban-seller@khl.app", "Urban Nest", "A modern apartment in a fast-growing corridor with good commuter links.", "https://images.unsplash.com/photo-1600585154524-36cb8cf2d747?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-juja-campus", "home", "Juja campus-side home", "Ksh 17,500 / month", "Juja", "Affordable", "urban-seller@khl.app", "Urban Nest", "A practical rental suited to young professionals and campus-adjacent tenants.", "https://images.unsplash.com/photo-1600607687641-2c2d9c1d0f2e?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-kiambu-garden", "home", "Kiambu garden apartment", "Ksh 28,800 / month", "Kiambu", "Featured", "garden-seller@khl.app", "Garden Estates", "A green-edge apartment with balanced finishes and a suburban calm.", "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-loresho-quiet", "home", "Loresho quiet apartment", "Ksh 43,000 / month", "Loresho", "Premium", "garden-seller@khl.app", "Garden Estates", "A quiet premium apartment with roomy interiors and calm estate access.", "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=900&q=80"),
  buildListing("airbnb-kilifi-escape", "airbnb", "Kilifi escape suite", "Ksh 7,100 / night", "Kilifi", "Relaxed", "coast-seller@khl.app", "Coastline Hosts", "A short-stay coastal suite with soft light and a calm setup.", "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=900&q=80"),
  buildListing("airbnb-bamburi-ocean", "airbnb", "Bamburi ocean apartment", "Ksh 7,900 / night", "Bamburi", "Popular", "coast-seller@khl.app", "Coastline Hosts", "Short-stay apartment with easy access to the beach and leisure spots.", "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=900&q=80"),
  buildListing("hotel-machakos-serene", "hotel", "Serene Plains Hotel", "Ksh 8,900 / night", "Machakos", "Value", "rift-seller@khl.app", "Rift Valley Lets", "A smart overnight option for town visits and business stays.", "https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?auto=format&fit=crop&w=900&q=80"),
  buildListing("hotel-kakamega-forest", "hotel", "Forest Gate Hotel", "Ksh 9,400 / night", "Kakamega", "New", "lake-seller@khl.app", "Lakefront Living", "A calm regional hotel with polished rooms and practical service.", "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=900&q=80"),
  buildListing("restaurant-nanyuki-supper", "restaurant", "Nanyuki Supper Club", "Ksh 3,300 / meal", "Nanyuki", "Featured", "highland-seller@khl.app", "Highland Homes", "Curated dining and a refined atmosphere for special nights out.", "https://images.unsplash.com/photo-1508424757105-b6d5ad9329d0?auto=format&fit=crop&w=900&q=80"),
  buildListing("restaurant-lamu-courtyard", "restaurant", "Lamu Courtyard Kitchen", "Ksh 2,900 / meal", "Lamu", "Premium", "coast-seller@khl.app", "Coastline Hosts", "Traditional flavors served in a beautiful open-air courtyard setting.", "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=900&q=80"),
  buildListing("home-kitengela-duplex", "home", "Kitengela duplex home", "Ksh 18,500 / month", "Kitengela", "Affordable", "rift-seller@khl.app", "Rift Valley Lets", "A practical family duplex in a growing residential area.", "https://images.unsplash.com/photo-1576941089067-2de3c901e126?auto=format&fit=crop&w=900&q=80"),
  buildListing("airbnb-meru-weekend", "airbnb", "Meru weekend apartment", "Ksh 5,800 / night", "Meru", "Value", "highland-seller@khl.app", "Highland Homes", "A clean furnished stay for quick visits and short getaways.", "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=80"),
  buildListing("hotel-garissa-river", "hotel", "Riverstone Hotel", "Ksh 8,100 / night", "Garissa", "Affordable", "rift-seller@khl.app", "Rift Valley Lets", "Straightforward hospitality with conference-friendly amenities.", "https://images.unsplash.com/photo-1455587734955-081b22074882?auto=format&fit=crop&w=900&q=80"),
  buildListing("restaurant-kisii-corner", "restaurant", "Kisii Corner Table", "Ksh 1,850 / meal", "Kisii", "Value", "lake-seller@khl.app", "Lakefront Living", "A relaxed local favorite for lunch meetings and family dinners.", "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=900&q=80")
];

export const getMarketplaceListings = () => [...seedListings, ...getCustomListings()];
